from hexlet_tasks import *


# print(is_palindrome("ишак ищет у тещи каши"))
# print(filter_string("A     N aS ta sia   ", "a"))
# print(has_char("Anastasia", "n"))
# print(my_substr_1("string", 3))
# print(my_substr_2("string", 3))
# print(join_numbers_from_range(0, 4))
# print(print_numbers(3))
# print(normalize_url("АДРЕС"))
# print(string_or_not(""))
# print(is_leap_year(2001))
# print(has_upper_case("вап4567гоШГНЕП"))
# print(get_age_difference(2018, 2001))
# print(letter_multiply("python", "py", 3))
# print(trim_and_repeat("python", 1, 1))
# print(get_hidden_card('1234567812345678', 3))
# print(truncate('hexlet', 2))
# print(sum_module(-1, 2))
# print(print_few_times("times", 3))
